//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `config.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package config;

/**
 * Helper class for marshaling/unmarshaling ObjectInformationSequence.
 **/
public final class ObjectInformationSequenceHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ObjectInformation[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ObjectInformation.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ObjectInformation[] read(com.zeroc.Ice.InputStream istr)
    {
        final ObjectInformation[] v;
        final int len0 = istr.readAndCheckSeqSize(2);
        v = new ObjectInformation[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ObjectInformation.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ObjectInformation[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ObjectInformation[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ObjectInformationSequenceHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ObjectInformation[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ObjectInformation[] v;
            v = ObjectInformationSequenceHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
