//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `config.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package config;

public class ObjectInformation implements java.lang.Cloneable,
                                          java.io.Serializable
{
    public String category;

    public String name;

    public ObjectInformation()
    {
        this.category = "";
        this.name = "";
    }

    public ObjectInformation(String category, String name)
    {
        this.category = category;
        this.name = name;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ObjectInformation r = null;
        if(rhs instanceof ObjectInformation)
        {
            r = (ObjectInformation)rhs;
        }

        if(r != null)
        {
            if(this.category != r.category)
            {
                if(this.category == null || r.category == null || !this.category.equals(r.category))
                {
                    return false;
                }
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::config::ObjectInformation");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, category);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        return h_;
    }

    public ObjectInformation clone()
    {
        ObjectInformation c = null;
        try
        {
            c = (ObjectInformation)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.category);
        ostr.writeString(this.name);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.category = istr.readString();
        this.name = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ObjectInformation v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ObjectInformation ice_read(com.zeroc.Ice.InputStream istr)
    {
        ObjectInformation v = new ObjectInformation();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ObjectInformation> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ObjectInformation v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ObjectInformation> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ObjectInformation.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ObjectInformation _nullMarshalValue = new ObjectInformation();

    /** @hidden */
    public static final long serialVersionUID = -7458585272011022769L;
}
