//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `frige.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.fridge;

/** @hidden */
public class _BasicFridgePrxI extends com.zeroc.Ice._ObjectPrxI implements BasicFridgePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
