//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `frige.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.fridge;

public class NoProduct extends com.zeroc.Ice.UserException
{
    public NoProduct()
    {
    }

    public NoProduct(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::device::fridge::NoProduct";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::device::fridge::NoProduct", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -6072628884807490994L;
}
