//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `frige.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.fridge;

public class Product implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String name;

    public double size;

    public String expirationDate;

    public Product()
    {
        this.name = "";
        this.expirationDate = "";
    }

    public Product(String name, double size, String expirationDate)
    {
        this.name = name;
        this.size = size;
        this.expirationDate = expirationDate;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Product r = null;
        if(rhs instanceof Product)
        {
            r = (Product)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.size != r.size)
            {
                return false;
            }
            if(this.expirationDate != r.expirationDate)
            {
                if(this.expirationDate == null || r.expirationDate == null || !this.expirationDate.equals(r.expirationDate))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::device::fridge::Product");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, size);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, expirationDate);
        return h_;
    }

    public Product clone()
    {
        Product c = null;
        try
        {
            c = (Product)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeDouble(this.size);
        ostr.writeString(this.expirationDate);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.size = istr.readDouble();
        this.expirationDate = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Product v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Product ice_read(com.zeroc.Ice.InputStream istr)
    {
        Product v = new Product();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Product> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Product v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Product> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Product.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Product _nullMarshalValue = new Product();

    /** @hidden */
    public static final long serialVersionUID = -4880042061217056647L;
}
