//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `frige.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.fridge;

/**
 * Helper class for marshaling/unmarshaling Products.
 **/
public final class ProductsHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Product[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Product.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Product[] read(com.zeroc.Ice.InputStream istr)
    {
        final Product[] v;
        final int len0 = istr.readAndCheckSeqSize(10);
        v = new Product[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Product.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Product[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Product[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ProductsHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Product[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Product[] v;
            v = ProductsHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
