#!/bin/bash

SERVERS_PATH=/home/pepe/Projekty/Semestr6/Rozproszone/lab_zookeeper/Classes/apache-zookeeper-3.8.0-bin;
DATA_DIR_PATH=/tmp/zookeeper;

# Add myid file to directories
for i in {1..3}
do
  mkdir -p "${DATA_DIR_PATH}/zk${i}";
  echo "$i" >> "${DATA_DIR_PATH}/zk${i}/myid";
done

# Run servers
for i in {1..3}
do
  ${SERVERS_PATH}/bin/zkServer.sh start "${SERVERS_PATH}/conf/zoo${i}.cfg";
done



