#!/bin/bash

SERVERS_PATH=/home/pepe/Projekty/Semestr6/Rozproszone/lab_zookeeper/Classes/apache-zookeeper-3.8.0-bin;

# Run servers
for i in {1..3}
do
  ${SERVERS_PATH}/bin/zkServer.sh stop "${SERVERS_PATH}/conf/zoo${i}.cfg";
done
