//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `lamp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.lamp;

/** @hidden */
public class _RgbLampPrxI extends com.zeroc.Ice._ObjectPrxI implements RgbLampPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
