//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `lamp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.lamp;

public class PowerLevelOutOfRange extends com.zeroc.Ice.UserException
{
    public PowerLevelOutOfRange()
    {
    }

    public PowerLevelOutOfRange(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::device::lamp::PowerLevelOutOfRange";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::device::lamp::PowerLevelOutOfRange", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -2772257558482564194L;
}
