//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `lamp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.lamp;

public class RgbColorIsIncorect extends com.zeroc.Ice.UserException
{
    public RgbColorIsIncorect()
    {
    }

    public RgbColorIsIncorect(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::device::lamp::RgbColorIsIncorect";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::device::lamp::RgbColorIsIncorect", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -1876785079402814796L;
}
