//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `lamp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.lamp;

public class RgbColor implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public int red;

    public int green;

    public int blue;

    public RgbColor()
    {
    }

    public RgbColor(int red, int green, int blue)
    {
        this.red = red;
        this.green = green;
        this.blue = blue;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RgbColor r = null;
        if(rhs instanceof RgbColor)
        {
            r = (RgbColor)rhs;
        }

        if(r != null)
        {
            if(this.red != r.red)
            {
                return false;
            }
            if(this.green != r.green)
            {
                return false;
            }
            if(this.blue != r.blue)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::device::lamp::RgbColor");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, red);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, green);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, blue);
        return h_;
    }

    public RgbColor clone()
    {
        RgbColor c = null;
        try
        {
            c = (RgbColor)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.red);
        ostr.writeInt(this.green);
        ostr.writeInt(this.blue);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.red = istr.readInt();
        this.green = istr.readInt();
        this.blue = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RgbColor v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RgbColor ice_read(com.zeroc.Ice.InputStream istr)
    {
        RgbColor v = new RgbColor();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RgbColor> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RgbColor v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(12);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<RgbColor> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(RgbColor.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RgbColor _nullMarshalValue = new RgbColor();

    /** @hidden */
    public static final long serialVersionUID = 5805225012605448056L;
}
