//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `lamp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.lamp;

public interface RgbLampPrx extends ClassicLampPrx
{
    default void setRgbColor(RgbColor rgbColor)
        throws RgbColorIsIncorect
    {
        setRgbColor(rgbColor, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setRgbColor(RgbColor rgbColor, java.util.Map<String, String> context)
        throws RgbColorIsIncorect
    {
        try
        {
            _iceI_setRgbColorAsync(rgbColor, context, true).waitForResponseOrUserEx();
        }
        catch(RgbColorIsIncorect ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setRgbColorAsync(RgbColor rgbColor)
    {
        return _iceI_setRgbColorAsync(rgbColor, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setRgbColorAsync(RgbColor rgbColor, java.util.Map<String, String> context)
    {
        return _iceI_setRgbColorAsync(rgbColor, context, false);
    }

    /**
     * @hidden
     * @param iceP_rgbColor -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setRgbColorAsync(RgbColor iceP_rgbColor, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setRgbColor", null, sync, _iceE_setRgbColor);
        f.invoke(true, context, null, ostr -> {
                     RgbColor.ice_write(ostr, iceP_rgbColor);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setRgbColor =
    {
        RgbColorIsIncorect.class
    };

    default RgbColor getRgbColor()
    {
        return getRgbColor(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RgbColor getRgbColor(java.util.Map<String, String> context)
    {
        return _iceI_getRgbColorAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<RgbColor> getRgbColorAsync()
    {
        return _iceI_getRgbColorAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RgbColor> getRgbColorAsync(java.util.Map<String, String> context)
    {
        return _iceI_getRgbColorAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RgbColor> _iceI_getRgbColorAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RgbColor> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getRgbColor", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     RgbColor ret;
                     ret = RgbColor.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RgbLampPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), RgbLampPrx.class, _RgbLampPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RgbLampPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), RgbLampPrx.class, _RgbLampPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RgbLampPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), RgbLampPrx.class, _RgbLampPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RgbLampPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), RgbLampPrx.class, _RgbLampPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static RgbLampPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, RgbLampPrx.class, _RgbLampPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static RgbLampPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, RgbLampPrx.class, _RgbLampPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default RgbLampPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (RgbLampPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default RgbLampPrx ice_adapterId(String newAdapterId)
    {
        return (RgbLampPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default RgbLampPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (RgbLampPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default RgbLampPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (RgbLampPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default RgbLampPrx ice_invocationTimeout(int newTimeout)
    {
        return (RgbLampPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default RgbLampPrx ice_connectionCached(boolean newCache)
    {
        return (RgbLampPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default RgbLampPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (RgbLampPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RgbLampPrx ice_secure(boolean b)
    {
        return (RgbLampPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default RgbLampPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (RgbLampPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RgbLampPrx ice_preferSecure(boolean b)
    {
        return (RgbLampPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default RgbLampPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (RgbLampPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default RgbLampPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (RgbLampPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default RgbLampPrx ice_collocationOptimized(boolean b)
    {
        return (RgbLampPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default RgbLampPrx ice_twoway()
    {
        return (RgbLampPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default RgbLampPrx ice_oneway()
    {
        return (RgbLampPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default RgbLampPrx ice_batchOneway()
    {
        return (RgbLampPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default RgbLampPrx ice_datagram()
    {
        return (RgbLampPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default RgbLampPrx ice_batchDatagram()
    {
        return (RgbLampPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default RgbLampPrx ice_compress(boolean co)
    {
        return (RgbLampPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default RgbLampPrx ice_timeout(int t)
    {
        return (RgbLampPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default RgbLampPrx ice_connectionId(String connectionId)
    {
        return (RgbLampPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default RgbLampPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (RgbLampPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::device::lamp::RgbLamp";
    }
}
