//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `lamp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package device.lamp;

public interface RgbLamp extends ClassicLamp
{
    void setRgbColor(RgbColor rgbColor, com.zeroc.Ice.Current current)
        throws RgbColorIsIncorect;

    RgbColor getRgbColor(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::device::lamp::ClassicLamp",
        "::device::lamp::RgbLamp"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::device::lamp::RgbLamp";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setRgbColor(RgbLamp obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        RgbColor iceP_rgbColor;
        iceP_rgbColor = RgbColor.ice_read(istr);
        inS.endReadParams();
        obj.setRgbColor(iceP_rgbColor, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getRgbColor(RgbLamp obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        RgbColor ret = obj.getRgbColor(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RgbColor.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getLampPower",
        "getLampStatus",
        "getRgbColor",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "setLampPower",
        "setLampStatus",
        "setRgbColor"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return ClassicLamp._iceD_getLampPower(this, in, current);
            }
            case 1:
            {
                return ClassicLamp._iceD_getLampStatus(this, in, current);
            }
            case 2:
            {
                return _iceD_getRgbColor(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 7:
            {
                return ClassicLamp._iceD_setLampPower(this, in, current);
            }
            case 8:
            {
                return ClassicLamp._iceD_setLampStatus(this, in, current);
            }
            case 9:
            {
                return _iceD_setRgbColor(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
